Fix findroot loop when the password to any encrypted device is unknown (#342)
Do this by asking max 6 times for a password, then continue with the next device.

Also fix a bug when an encrypted device on LVM leads to the same device
name for the encrypted and unencrypted device.

diff --git a/airootfs/etc/initcpio/hooks/findroot b/airootfs/etc/initcpio/hooks/findroot
--- a/airootfs/etc/initcpio/hooks/findroot
+++ b/airootfs/etc/initcpio/hooks/findroot
@@ -17,12 +17,15 @@ run_hook() {
         if cryptsetup isLuks ${curdev} >/dev/null 2>&1
         then
             echo "A passphrase is required to access device ${curdev}:"
-            local cryptname="${curdev##*/}"
+            local cryptname="luks-${curdev##*/}"
             local cryptargs=""
-            while ! eval cryptsetup open --type luks ${curdev} ${cryptname} ${cryptargs}
-            do
-                sleep 2;
-            done
+            if ! cryptsetup open --type luks ${curdev} ${cryptname} ${cryptargs}; then
+                if ! cryptsetup open --type luks ${curdev} ${cryptname} ${cryptargs}; then
+                    # each cryptsetup call offers 3 tries to enter a valid password
+                    # all 6 failed failed, so continue with the next device
+                    continue
+                fi
+            fi
             if [ ! -e "/dev/mapper/${cryptname}" ]
             then
                 err "Password succeeded but ${cryptname} creation failed, aborting..."
